In [ ]:
def func_va(*args):
  print(args)

def func_kw(**kwargs):
  print(kwargs)

In [ ]:
func_va(2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4)

(2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4)


In [ ]:
dc = {str(key): val for key, val in enumerate(range(5))}

In [ ]:
func_kw(**dc)

{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4}


In [ ]:
import numpy as np

In [ ]:
data_array = np.array(list(range(10)))
print(type(data_array))
print(data_array)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
lista1 = []
lista1.append(list(range(5)))
lista1.append(list(range(5, 10)))

print(lista1)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


In [ ]:
array2 = np.array([[1,2,3,4], [5,6,7,8]]) #array 4x2
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
array3 = np.array([list(range(5)), list(range(5, 10)), list(range(10, 15))])
print(array3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
range_array = np.arange(10)
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
range_array = np.arange(1, 2, .3)
print(range_array)

[1.  1.3 1.6 1.9]


In [ ]:
range_array = np.arange(1, 2, .03)
print(range_array)

[1.   1.03 1.06 1.09 1.12 1.15 1.18 1.21 1.24 1.27 1.3  1.33 1.36 1.39
 1.42 1.45 1.48 1.51 1.54 1.57 1.6  1.63 1.66 1.69 1.72 1.75 1.78 1.81
 1.84 1.87 1.9  1.93 1.96 1.99]


In [ ]:
range_array = np.arange(1, 1.5, .01)
print(range_array)

[1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.12 1.13
 1.14 1.15 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25 1.26 1.27
 1.28 1.29 1.3  1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39 1.4  1.41
 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49]


Shape indica a dimensão do array

In [ ]:
array2.shape

(2, 4)

In [ ]:
array3.shape

(3, 5)

In [ ]:
data_random = np.random.randn(3,3)

print(data_random)

[[ 0.84465077 -0.88767531 -0.38724448]
 [ 0.47245046 -0.0157899  -0.83009578]
 [-0.59781574  0.40949817  0.11729298]]


#funções para criar arrays

1.   array
2.   asarray
3. arange
4. ones, ones_like
5. zeros, zeros_like
6. empty, empty_like
7. full, full_like
8. eye, identity



In [ ]:
# tamanho de cada item do array em bits
array2.itemsize

8

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)

#multiplicando array
print(arr * arr)

#elevando à potencia
print(arr ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[1., 2., 7.], [4., 5., 6.]])

print(arr == arr2)

[[ True  True False]
 [ True  True  True]]


In [ ]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8 ])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


In [ ]:
arr[5:8] = 12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [ ]:
#array bidimensional
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr2d.shape

(3, 3)

In [ ]:
#linha 2 
arr2d[2]

array([7, 8, 9])

In [ ]:
#linha 2, coluna 1
print(arr2d[2][1])
#ou
print(arr2d[2, 1]) 

8
8


In [ ]:
#tres dimensões
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
print(arr3d.ndim)
print(arr3d)

3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#diminui uma dimensão
print(arr3d[0].ndim)
print(arr3d[0])

2
[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr3d[1, 0])

[7 8 9]


In [ ]:
array_x = np.array([[7, 8, 9], [4, 5, 6]])
print(array_x)

#mudar o formato
array_x.reshape(3,2)

[[7 8 9]
 [4 5 6]]


array([[7, 8],
       [9, 4],
       [5, 6]])

In [ ]:
array_x = np.array([[7, 8, 9], [4, 5, 6]])
print(array_x)

#muda o tamanho
array_x.resize(3,2)
print(array_x)


[[7 8 9]
 [4 5 6]]
[[7 8]
 [9 4]
 [5 6]]
